# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import api.services.featurizer.featurizer_service_pb2 as featurizer__service__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION,
        GRPC_GENERATED_VERSION,
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        " but the generated code in featurizer_service_pb2_grpc.py depends on"
        f" grpcio>={GRPC_GENERATED_VERSION}."
        f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.",
    )


class FeaturizerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Build = channel.unary_unary(
            "/featurizer_service.FeaturizerService/Build",
            request_serializer=featurizer__service__pb2.FeaturizerServiceRequest.SerializeToString,
            response_deserializer=featurizer__service__pb2.FeaturizerServiceResponse.FromString,
            _registered_method=True,
        )


class FeaturizerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Build(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FeaturizerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Build": grpc.unary_unary_rpc_method_handler(
            servicer.Build,
            request_deserializer=featurizer__service__pb2.FeaturizerServiceRequest.FromString,
            response_serializer=featurizer__service__pb2.FeaturizerServiceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "featurizer_service.FeaturizerService",
        rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "featurizer_service.FeaturizerService",
        rpc_method_handlers,
    )


# This class is part of an EXPERIMENTAL API.
class FeaturizerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Build(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/featurizer_service.FeaturizerService/Build",
            featurizer__service__pb2.FeaturizerServiceRequest.SerializeToString,
            featurizer__service__pb2.FeaturizerServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
