# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: featurizer_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "featurizer_service.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18\x66\x65\x61turizer_service.proto\x12\x12\x66\x65\x61turizer_service":\n\x16\x46\x65\x61turizerServiceInput\x12\x12\n\ntimestamps\x18\x01 \x03(\x01\x12\x0c\n\x04keys\x18\x02 \x03(\x05"]\n\x18\x46\x65\x61turizerServiceRequest\x12\x41\n\rlast_accesses\x18\x01 \x03(\x0b\x32*.featurizer_service.FeaturizerServiceInput"k\n\x19\x46\x65\x61turizerServiceResponse\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\x12\x10\n\x08keys_seq\x18\x02 \x03(\x05\x12\x16\n\x0e\x66\x65\x61tures_shape\x18\x03 \x03(\x05\x12\x12\n\nkeys_shape\x18\x04 \x03(\x05\x32y\n\x11\x46\x65\x61turizerService\x12\x64\n\x05\x42uild\x12,.featurizer_service.FeaturizerServiceRequest\x1a-.featurizer_service.FeaturizerServiceResponseb\x06proto3',
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR,
    "featurizer_service_pb2",
    _globals,
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FEATURIZERSERVICEINPUT"]._serialized_start = 48
    _globals["_FEATURIZERSERVICEINPUT"]._serialized_end = 106
    _globals["_FEATURIZERSERVICEREQUEST"]._serialized_start = 108
    _globals["_FEATURIZERSERVICEREQUEST"]._serialized_end = 201
    _globals["_FEATURIZERSERVICERESPONSE"]._serialized_start = 203
    _globals["_FEATURIZERSERVICERESPONSE"]._serialized_end = 310
    _globals["_FEATURIZERSERVICE"]._serialized_start = 312
    _globals["_FEATURIZERSERVICE"]._serialized_end = 433
# @@protoc_insertion_point(module_scope)
