# Google Cloud Build configuration:
# Build and push Docker images to Google Artifact Registry
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'src/api/gateway/Dockerfile', '-t', '${_CR_URL}/api-gateway:${_GIT_HUB_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'src/api/services/decider/Dockerfile', '-t', '${_CR_URL}/decider-service:${_GIT_HUB_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'src/api/services/featurizer/Dockerfile', '-t', '${_CR_URL}/featurizer-service:${_GIT_HUB_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'src/api/services/predictor/Dockerfile', '-t', '${_CR_URL}/predictor-service:${_GIT_HUB_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'src/api/services/scorer/Dockerfile', '-t', '${_CR_URL}/scorer-service:${_GIT_HUB_SHA}', '.']

images:
  - '${_CR_URL}/api-gateway:${_GIT_HUB_SHA}'
  - '${_CR_URL}/decider-service:${_GIT_HUB_SHA}'
  - '${_CR_URL}/featurizer-service:${_GIT_HUB_SHA}'
  - '${_CR_URL}/predictor-service:${_GIT_HUB_SHA}'
  - '${_CR_URL}/scorer-service:${_GIT_HUB_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY