PIPELINE_PHASE_CONFIGURATION = "configuration"
PIPELINE_PHASE_DATA_GENERATION = "data generation"

CONFIG_FILE_NAME = "config.yaml"
CONFIG_FILE_PARENT_LEVEL = 5

MIN_HOUR = 0
MAX_HOUR = 23

TRAINING_OPTIMIZER_ADAM = "adam"
TRAINING_OPTIMIZER_ADAMW = "adamw"
TRAINING_OPTIMIZER_SGD = "sgd"
ALLOWED_TRAINING_OPTIMIZERS = [
    TRAINING_OPTIMIZER_ADAM,
    TRAINING_OPTIMIZER_ADAMW,
    TRAINING_OPTIMIZER_SGD,
]

DATA_DISTRIBUTION_STATIC_MODE = "static"
DATA_DISTRIBUTION_DYNAMIC_MODE = "dynamic"
ALLOWED_DATA_DISTRIBUTION_MODES = [
    DATA_DISTRIBUTION_STATIC_MODE,
    DATA_DISTRIBUTION_DYNAMIC_MODE,
]

TIMESTAMP_COLUMN_NAME = "timestamp"
REQUEST_COLUMN_NAME = "request"
