services:
  api_gateway:
    build:
      context: ./
      dockerfile: src/api/gateway/Dockerfile
      args:
        GATEWAY_API_PORT: ${GATEWAY_API_PORT}
    environment:
      - FEATURIZER_SERVICE_CHANNEL=${FEATURIZER_SERVICE_CHANNEL}
      - PREDICTOR_SERVICE_CHANNEL=${PREDICTOR_SERVICE_CHANNEL}
      - SCORER_SERVICE_CHANNEL=${SCORER_SERVICE_CHANNEL}
      - DECIDER_SERVICE_CHANNEL=${DECIDER_SERVICE_CHANNEL}
      - GRAFANA_LOKI_URL=${GRAFANA_LOKI_URL}
      - GRAFANA_LOKI_USER_ID=${GRAFANA_LOKI_USER_ID}
      - GRAFANA_LOKI_TOKEN=${GRAFANA_LOKI_TOKEN}
    ports:
      - "${GATEWAY_API_PORT}:${GATEWAY_API_PORT}"
    depends_on:
      - featurizer_service
      - predictor_service
      - scorer_service
      - decider_service

  featurizer_service:
    build:
      context: ./
      dockerfile: src/api/services/featurizer/Dockerfile
      args:
        FEATURIZER_SERVICE_PORT: ${FEATURIZER_SERVICE_PORT}
    environment:
      - FEATURIZER_SERVICE_CHANNEL=${FEATURIZER_SERVICE_CHANNEL}
    ports:
      - "${FEATURIZER_SERVICE_PORT}:${FEATURIZER_SERVICE_PORT}"

  predictor_service:
    build:
      context: ./
      dockerfile: src/api/services/predictor/Dockerfile
      args:
        PREDICTOR_SERVICE_PORT: ${PREDICTOR_SERVICE_PORT}
    environment:
      - PREDICTOR_SERVICE_CHANNEL=${PREDICTOR_SERVICE_CHANNEL}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_TRACKING_USERNAME=${DAGS_HUB_REPO_OWNER}
      - MLFLOW_TRACKING_PASSWORD=${DAGS_HUB_TOKEN}
    ports:
      - "${PREDICTOR_SERVICE_PORT}:${PREDICTOR_SERVICE_PORT}"

  scorer_service:
    build:
      context: ./
      dockerfile: src/api/services/scorer/Dockerfile
      args:
        SCORER_SERVICE_PORT: ${SCORER_SERVICE_PORT}
    environment:
      - SCORER_SERVICE_CHANNEL=${SCORER_SERVICE_CHANNEL}
    ports:
      - "${SCORER_SERVICE_PORT}:${SCORER_SERVICE_PORT}"

  decider_service:
    build:
      context: ./
      dockerfile: src/api/services/decider/Dockerfile
      args:
        DECIDER_SERVICE_PORT: ${DECIDER_SERVICE_PORT}
    environment:
      - DECIDER_SERVICE_CHANNEL=${DECIDER_SERVICE_CHANNEL}
    ports:
      - "${DECIDER_SERVICE_PORT}:${DECIDER_SERVICE_PORT}"
