[pytest]
markers =
    data.integrity.raw: Data Raw Integrity Tests with DeepChecks
    data.integrity.processed: Data Processed Integrity Tests with DeepChecks
    data.quality.raw: Data Raw Quality Tests with Great Expectations
    data.quality.processed: Data Processed Quality Tests with Great Expectations
    data.train_test_validation: Data Train-Test-Validation Tests with DeepChecks
    model.performance: Model Performance Tests with DeepChecks
    model.training: Model Training Tests
    model.training.end_to_end: Model Training End-To-End Test
    model.training.learnability: Model Training Learnability Test
    model.training.optimization_stability: Model Training Optimization Stability Test
    model.training.output_integrity: Model Training Output Integrity Test
    model.training.portability: Model Training Portability Test
