import numpy as np

from components.logs.levels.error_logger import error


def generate_distortion_pattern(
    distortion_interval: int,
    distortion_history: int,
    distortion_correction: int,
    requests: list[int],
    requests_count: int,
    keys_range_size: int,
    first_key: int,
    noise_min: int,
    noise_max: int,
) -> int:
    """Determine the next key to be accessed according to distortion pattern.

    This function determines which is the next key to be accessed according to
    distortion pattern. This pattern simulates two kinds of accesses: at fixed
    intervals corrective access is made based on history, otherwise noisy
    access is generated by adding random noise to the last accessed key.

    Args:
        distortion_interval (int): Number of requests between corrective
                                   accesses.
        distortion_history (int): Steps back in the requests history to
                                  pick the key for correction.
        distortion_correction (int): Offset to apply during corrective access.
        requests (list[int]): List of keys requested so far.
        requests_count (int): Number of requests generated so far.
        keys_range_size (int): Total number of available keys.
        first_key (int): Minimum key in the range.
        noise_min (int): Minimum noise value to add to the last key.
        noise_max (int): Maximum noise value to add to the last key.

    Returns:
        int: Index of the next accessed key.

    Raises:
        RuntimeError: If generating the distortion pattern fails:
            * Accessing the request history due to empty or too short list
              (IndexError, ValueError).
            * Using invalid numeric arguments or ranges
              (TypeError, ValueError).
            * Random noise generation or arithmetic operations fail
              due to invalid inputs (ValueError, TypeError).
    """
    try:
        # Check whether requests list
        # is empty
        if not requests:
            msg = "Requests list is empty, cannot generate distortion pattern"
            error(
                msg,
                extra={
                    "requests_count": requests_count,
                    "keys_range_len": keys_range_size,
                    "first_key": first_key,
                    "context": "Distortion pattern generation",
                },
            )
            raise ValueError(msg)

        # Based on a distortion interval
        if requests_count % distortion_interval == 0:
            # Make a regular corrective key access,
            # looking back at distortion history requests,
            # adding a correction
            requested_key = (
                (
                    requests[-distortion_history]
                    - first_key
                    + distortion_correction
                )
                % keys_range_size
            ) + first_key
        else:
            # Make a noisy key request by
            # taking the last accessed key and
            # adding random noise (within noise min and max)
            noise = np.random.randint(noise_min, noise_max + 1)
            requested_key = (
                (requests[-1] - first_key + noise) % keys_range_size
            ) + first_key

        return requested_key
    except (IndexError, TypeError, ValueError) as e:
        msg = "Distortion pattern generation failed"
        error(
            msg,
            extra={
                "exception": str(e),
                "distortion_interval": distortion_interval,
                "distortion_history": distortion_history,
                "distortion_correction": distortion_correction,
                "requests_count": requests_count,
                "requests_num": len(requests) if requests else 0,
                "keys_range_len": keys_range_size,
                "first_key": first_key,
                "noise_min": noise_min,
                "noise_max": noise_max,
                "context": "Distortion pattern generation",
            },
        )
        raise RuntimeError(msg) from e
