from typing import List

import numpy as np

from components.logs.levels.debug_logger import debug
from components.logs.levels.error_logger import error
from components.logs.levels.info_logger import info


def generate_distortion_pattern(
    distortion_interval: int,
    distortion_history: int,
    distortion_correction: int,
    requests: List[int],
    requests_count: int,
    keys_range_size: int,
    first_key: int,
    noise_min: int,
    noise_max: int,
) -> int:
    """
    Determine the next key to be accessed
    according to distortion pattern.

    This function determines which is the next
    key to be accessed according to distortion
    pattern. This pattern simulates two kinds of
    accesses: at fixed intervals corrective
    access is made based on history, otherwise
    noisy access is generated by adding random
    noise to the last accessed key.

    Args:
        distortion_interval (int): Number of requests between
                                   corrective accesses.
        distortion_history (int): Steps back in the requests history
                                  to pick the key for correction.
        distortion_correction (int): Offset to apply during corrective access.
        requests (List[int]): List of keys requested so far.
        requests_count (int): Number of requests generated so far.
        keys_range_size (int): Total number of available keys.
        first_key (int): Minimum key in the range.
        noise_min (int): Minimum noise value to add to the last key.
        noise_max (int): Maximum noise value to add to the last key.

    Returns:
        int: Index of the next accessed key.

    Raises:
        ValueError: If requests is an empty list.
    """
    debug(f"Interval for distortion pattern: {distortion_interval}")

    # Check whether requests list
    # is empty
    if not requests:
        msg = "Requests list is empty, cannot generate distortion pattern"
        error("%s", msg)
        raise ValueError(msg)

    # Based on a distortion interval
    if requests_count % distortion_interval == 0:
        # Make a regular corrective key access,
        # looking back at distortion history requests,
        # adding a correction
        requested_key = (
            (requests[-distortion_history] - first_key + distortion_correction)
            % keys_range_size
        ) + first_key

        debug(
            f"Regular distorted key access with"
            f" history: {distortion_history}, and "
            f"correction: {distortion_correction}"
        )
    else:
        # Make a noisy key request by
        # taking the last accessed key and
        # adding random noise (within noise min and max)
        noise = np.random.randint(noise_min, noise_max + 1)
        requested_key = (
            (requests[-1] - first_key + noise) % keys_range_size
        ) + first_key

        debug(
            f"Noisy distorted key access with "
            f"noise: {noise} (within: {noise_min}, {noise_max})"
        )

    info(f"(Distortion pattern) Key requested: {requested_key}")

    return requested_key
