syntax = "proto3";

package scorer_service;

message ScorerServiceInput {
    repeated float outputs = 1;
    repeated float variances = 2;
}

message ScorerServiceRequest {
    repeated ScorerServiceInput last_accesses = 1;
    float conf_level = 2;
    float prob_weight = 3;
    float conf_weight = 4;
}

message ScorerServiceResponse {
    repeated float key_scores = 1;
    repeated float prob_matrix = 2;
    repeated float conf_matrix = 3;
}

service ScorerService {
    rpc Score(ScorerServiceRequest) returns (ScorerServiceResponse);
}
