{
 "title": "Cache Eviction Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Evicted Keys",
   "type": "stat",
   "description": "Cumulative number of keys evicted by the API over the last 5 minutes",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "keys" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(keys_evicted_tot_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evicted Keys (%)",
   "type": "gauge",
   "description": "Average proportion of cache keys evicted per request relative to total cache size over the last 5 minutes",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(keys_evicted_ratio[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Evicted Keys per Request",
   "type": "stat",
   "description": "Average number of keys evicted per API request over the last 5 minutes",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "keys/req" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(keys_evicted_tot_total[5m]))\n/\nsum(increase(http_requests_total{handler=\"/evict\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Excluded Keys",
   "type": "stat",
   "description": "Cumulative number of keys excluded from eviction by the API over the last 5 minutes",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "keys" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(keys_excluded_from_eviction_tot_total[5m]))\n/\nsum(increase(http_requests_total{handler=\"/evict\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Excluded Keys (%)",
   "type": "gauge",
   "description": "Average proportion of cache keys excluded from eviction relative to total cache size over the last 5 minutes",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(keys_excluded_from_eviction_ratio[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Excluded Keys per Request",
   "type": "stat",
   "description": "Average number of cache keys excluded from eviction per request over the last 5 minutes",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "keys/req" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(keys_excluded_from_eviction_tot_total[5m]))\n/\nsum(increase(http_requests_total{handler=\"/evict\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}