# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predictor_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "predictor_service.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17predictor_service.proto\x12\x11predictor_service",\n\nLastAccess\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x0b\n\x03key\x18\x02 \x01(\x05"\xbc\x01\n\x17PredictorServiceRequest\x12\x34\n\rlast_accesses\x18\x01 \x03(\x0b\x32\x1d.predictor_service.LastAccess\x12\x17\n\x0frollout_horizon\x18\x02 \x01(\x05\x12\x1a\n\x12mc_dropout_samples\x18\x03 \x01(\x05\x12\x1b\n\x13time_step_increment\x18\x04 \x01(\x02\x12\x19\n\x11unbiased_variance\x18\x05 \x01(\x08"z\n\x18PredictorServiceResponse\x12-\n\x07outputs\x18\x01 \x03(\x0b\x32\x1c.predictor_service.FloatList\x12/\n\tvariances\x18\x02 \x03(\x0b\x32\x1c.predictor_service.FloatList"\x1b\n\tFloatList\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32v\n\x10PredictorService\x12\x62\n\x07Predict\x12*.predictor_service.PredictorServiceRequest\x1a+.predictor_service.PredictorServiceResponseb\x06proto3',
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR,
    "predictor_service_pb2",
    _globals,
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LASTACCESS"]._serialized_start = 46
    _globals["_LASTACCESS"]._serialized_end = 90
    _globals["_PREDICTORSERVICEREQUEST"]._serialized_start = 93
    _globals["_PREDICTORSERVICEREQUEST"]._serialized_end = 281
    _globals["_PREDICTORSERVICERESPONSE"]._serialized_start = 283
    _globals["_PREDICTORSERVICERESPONSE"]._serialized_end = 405
    _globals["_FLOATLIST"]._serialized_start = 407
    _globals["_FLOATLIST"]._serialized_end = 434
    _globals["_PREDICTORSERVICE"]._serialized_start = 436
    _globals["_PREDICTORSERVICE"]._serialized_end = 554
# @@protoc_insertion_point(module_scope)
