apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  GATEWAY_API_PORT: "8000"
  FEATURIZER_SERVICE_CHANNEL: "featurizer-service:8001"
  PREDICTOR_SERVICE_CHANNEL: "predictor-service:8002"
  SCORER_SERVICE_CHANNEL: "scorer-service:8003"
  DECIDER_SERVICE_CHANNEL: "decider-service:8004"
