# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: decider_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "decider_service.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15\x64\x65\x63ider_service.proto\x12\x0f\x64\x65\x63ider_service"p\n\x15\x44\x65\x63iderServiceRequest\x12\x15\n\rkeys_in_cache\x18\x01 \x03(\x05\x12\x12\n\nkey_scores\x18\x02 \x03(\x02\x12\x15\n\rexcluded_keys\x18\x03 \x03(\x05\x12\x15\n\rnum_evictions\x18\x04 \x01(\x05"/\n\x16\x44\x65\x63iderServiceResponse\x12\x15\n\rkeys_to_evict\x18\x01 \x03(\x05\x32k\n\x0e\x44\x65\x63iderService\x12Y\n\x06\x44\x65\x63ide\x12&.decider_service.DeciderServiceRequest\x1a\'.decider_service.DeciderServiceResponseb\x06proto3',
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR,
    "decider_service_pb2",
    _globals,
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DECIDERSERVICEREQUEST"]._serialized_start = 42
    _globals["_DECIDERSERVICEREQUEST"]._serialized_end = 154
    _globals["_DECIDERSERVICERESPONSE"]._serialized_start = 156
    _globals["_DECIDERSERVICERESPONSE"]._serialized_end = 203
    _globals["_DECIDERSERVICE"]._serialized_start = 205
    _globals["_DECIDERSERVICE"]._serialized_end = 312
# @@protoc_insertion_point(module_scope)
