apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: featurizer-service
spec:
  podSelector:
    matchLabels:
      app: featurizer-service
  policyTypes:
    - Ingress
    - Egress
