apiVersion: apps/v1
kind: Deployment
metadata:
  name: featurizer-service
  namespace: featurizer-service
  annotations:
    kube-score/ignore: pod-networkpolicy,networkpolicy-targets-pod
  labels:
    app: featurizer-service
    role: featurizer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: featurizer-service
      role: featurizer-service
  template:
    metadata:
      annotations:
        kube-score/ignore: pod-networkpolicy,networkpolicy-targets-pod
      labels:
        app: featurizer-service
        role: featurizer-service
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        fsGroup: 2000
      containers:
      - name: featurizer-service
        image: europe-west4-docker.pkg.dev/lstm-cache-eviction-policy/lstm-cache-eviction-policy-cr/featurizer-service:PLACEHOLDER_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "echo ready"
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "echo ok"
          initialDelaySeconds: 10
          periodSeconds: 15
        envFrom:
        - configMapRef:
            name: featurizer-service-config
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 10001
          runAsGroup: 10001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "100Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: featurizer-service
  namespace: featurizer-service
spec:
  selector:
    app: featurizer-service
    role: featurizer-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
