resources:
  - ../../api-gateway
  - ../../decider-service
  - ../../featurizer-service
  - ../../predictor-service
  - ../../scorer-service

images:
  - name: europe-west4-docker.pkg.dev/lstm-cache-eviction-policy/lstm-cache-eviction-policy-cr/api-gateway
    newTag: PLACEHOLDER_SHA
  - name: europe-west4-docker.pkg.dev/lstm-cache-eviction-policy/lstm-cache-eviction-policy-cr/decider-service
    newTag: PLACEHOLDER_SHA
  - name: europe-west4-docker.pkg.dev/lstm-cache-eviction-policy/lstm-cache-eviction-policy-cr/featurizer-service
    newTag: PLACEHOLDER_SHA
  - name: europe-west4-docker.pkg.dev/lstm-cache-eviction-policy/lstm-cache-eviction-policy-cr/predictor-service
    newTag: PLACEHOLDER_SHA
  - name: europe-west4-docker.pkg.dev/lstm-cache-eviction-policy/lstm-cache-eviction-policy-cr/scorer-service
    newTag: PLACEHOLDER_SHA