from pathlib import Path

# ----------------------------
# Project
# ----------------------------
PROJECT_ROOT = Path(__file__).resolve().parent


# ----------------------------
# Configuration
# ----------------------------
API_CONFIG_FILE_PATH = PROJECT_ROOT / "meta_config.json"


# ----------------------------
# Kwargs
# ----------------------------
ROLLOUT_HORIZON_API_KWARG_NAME = "rollout_horizon"
MC_DROPOUT_SAMPLES_API_KWARG_NAME = "mc_dropout_samples"
CONFIDENCE_LEVEL_API_KWARG_NAME = "confidence_level"
TIME_STEP_INCREMENT_API_KWARG_NAME = "time_step_increment"
NUM_EVICTIONS_API_KWARG_NAME = "num_evictions"
EXCLUDED_KEYS_API_KWARG_NAME = "excluded_keys"
PROB_WEIGHT_API_KWARG_NAME = "prob_weight"
CONF_WEIGHT_API_KWARG_NAME = "conf_weight"
RETURN_ALL_SCORES_API_KWARG_NAME = "return_all_scores"
RETURN_PROB_CONF_API_KWARG_NAME = "return_prob_conf"

MAX_ROLLOUT_HORIZON = 50
MAX_MC_DROPOUT_SAMPLES = 1000
MAX_TIME_STEP_INCREMENT = 5.0

API_KWARGS = {
    ROLLOUT_HORIZON_API_KWARG_NAME,
    MC_DROPOUT_SAMPLES_API_KWARG_NAME,
    CONFIDENCE_LEVEL_API_KWARG_NAME,
    TIME_STEP_INCREMENT_API_KWARG_NAME,
    NUM_EVICTIONS_API_KWARG_NAME,
    EXCLUDED_KEYS_API_KWARG_NAME,
    PROB_WEIGHT_API_KWARG_NAME,
    CONF_WEIGHT_API_KWARG_NAME,
    RETURN_ALL_SCORES_API_KWARG_NAME,
    RETURN_PROB_CONF_API_KWARG_NAME,
}


# ----------------------------
# Gateway API
# ----------------------------
GATEWAY_API_ENDPOINT = "/evict"

GATEWAY_API_RETURN_KEYS_TO_EVICT_NAME = "keys_to_evict"
GATEWAY_API_RETURN_KEY_SCORES_NAME = "key_scores"
GATEWAY_API_RETURN_PROB_MATRIX_NAME = "prob_matrix"
GATEWAY_API_RETURN_CONF_MATRIX_NAME = "conf_matrix"
GATEWAY_API_RETURN_KWARGS_NAME = "kwargs"


# ----------------------------
# Predictor service
# ----------------------------
PREDICTOR_SERVICE_ENDPOINT = "/predictor"
PREDICTOR_SERVICE_URL = "http://127.0.0.1:8001" + PREDICTOR_SERVICE_ENDPOINT

PREDICTOR_SERVICE_LAST_ACCESSES_PARAM_NAME = "last_accesses"
PREDICTOR_SERVICE_MODEL_PATH_PARAM_NAME = "model_path"
PREDICTOR_SERVICE_MODEL_PARAMS_PARAM_NAME = "model_params"
PREDICTOR_SERVICE_DEVICE_TYPE_PARAM_NAME = "device_type"
PREDICTOR_SERVICE_MIN_KEY_PARAM_NAME = "min_key"
PREDICTOR_SERVICE_MAX_KEY_PARAM_NAME = "max_key"
PREDICTOR_SERVICE_NUM_FEATURES_PARAM_NAME = "num_features"
PREDICTOR_SERVICE_EMBEDDING_DIM_PARAM_NAME = "embedding_dim"
PREDICTOR_SERVICE_ROLLOUT_HORIZON_PARAM_NAME = "rollout_horizon"
PREDICTOR_SERVICE_MC_DROPOUT_SAMPLES_PARAM_NAME = "mc_dropout_samples"
PREDICTOR_SERVICE_TIME_STEP_INCREMENT_PARAM_NAME = "time_step_increment"

PREDICTOR_SERVICE_PARAMS = {
    PREDICTOR_SERVICE_LAST_ACCESSES_PARAM_NAME: None,
    PREDICTOR_SERVICE_MODEL_PATH_PARAM_NAME: None,
    PREDICTOR_SERVICE_MODEL_PARAMS_PARAM_NAME: None,
    PREDICTOR_SERVICE_DEVICE_TYPE_PARAM_NAME: None,
    PREDICTOR_SERVICE_MIN_KEY_PARAM_NAME: None,
    PREDICTOR_SERVICE_MAX_KEY_PARAM_NAME: None,
    PREDICTOR_SERVICE_NUM_FEATURES_PARAM_NAME: None,
    PREDICTOR_SERVICE_EMBEDDING_DIM_PARAM_NAME: None,
    PREDICTOR_SERVICE_ROLLOUT_HORIZON_PARAM_NAME: None,
    PREDICTOR_SERVICE_MC_DROPOUT_SAMPLES_PARAM_NAME: None,
    PREDICTOR_SERVICE_TIME_STEP_INCREMENT_PARAM_NAME: None,
}

PREDICTOR_SERVICE_RETURN_OUTPUTS_NAME = "outputs"
PREDICTOR_SERVICE_RETURN_VARIANCES_NAME = "variances"


# ----------------------------
# Scorer service
# ----------------------------
SCORER_SERVICE_ENDPOINT = "/scorer"
SCORER_SERVICE_URL = "http://127.0.0.1:8002" + SCORER_SERVICE_ENDPOINT

SCORER_SERVICE_OUTPUTS_PARAM_NAME = "outputs"
SCORER_SERVICE_VARIANCES_PARAM_NAME = "variances"
SCORER_SERVICE_CONFIDENCE_LEVEL_PARAM_NAME = "confidence_level"
SCORER_SERVICE_PROB_WEIGHT_PARAM_NAME = "prob_weight"
SCORER_SERVICE_CONF_WEIGHT_PARAM_NAME = "conf_weight"

SCORER_SERVICE_PARAMS = {
    SCORER_SERVICE_OUTPUTS_PARAM_NAME: None,
    SCORER_SERVICE_VARIANCES_PARAM_NAME: None,
    SCORER_SERVICE_CONFIDENCE_LEVEL_PARAM_NAME: None,
    SCORER_SERVICE_PROB_WEIGHT_PARAM_NAME: None,
    SCORER_SERVICE_CONF_WEIGHT_PARAM_NAME: None,
}

SCORER_SERVICE_RETURN_KEY_SCORES_NAME = "key_scores"
SCORER_SERVICE_RETURN_PROB_MATRIX_NAME = "prob_matrix"
SCORER_SERVICE_RETURN_CONF_MATRIX_NAME = "conf_matrix"
