apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: scorer-service
  annotations:
    kube-score/ignore: pod-networkpolicy,networkpolicy-targets-pod
spec:
  podSelector:
    matchLabels:
      app: scorer-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: [ ]
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to: [ ]
