apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: predictor-service
  annotations:
    kube-score/ignore: pod-networkpolicy,networkpolicy-targets-pod,container-readonly-root-filesystem
spec:
  podSelector:
    matchLabels:
      app: predictor-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
