resources:
  device:
    type: cpu
kwargs:
  rollout_horizon:
    value: 3
    max: 10
  mc_dropout_samples:
    value: 10
    max: 25
  conf_level:
    value: 0.95
  time_step_increment:
    value: 0.02
    max: 5.0
  num_evictions:
    value: 1
  excluded_keys:
    value: [ ]
  unbiased_variance:
    value: true
  conf_weight:
    value: 0.7
logs:
  level: INFO
model:
  optimizations:
    quantization:
      engine: qnnpack
