hardware:
  device:
    type: cpu
kwargs:
  rollout_horizon:
    value: 5
    max: 50
  mc_dropout_samples:
    value: 25
    max: 100
  confidence_level:
    value: 0.95
  time_step_increment:
    value: 0.05
    max: 5.0
  num_evictions:
    value: 1
  excluded_keys:
    value: [ ]
  unbiased_variance:
    value: true
  prob_weight:
    value: 0.8
  conf_weight:
    value: 0.2
  return_all_scores:
    value: false
  return_prob_conf:
    value: false
  return_api_kwargs:
    value: false
logs:
  level: INFO
model:
  optimizations:
    quantization:
      engine: qnnpack
