hardware:
  device:
    type: mps
api_kwargs:
  rollout_horizon:
    default: 5
    max: 50
  mc_dropout_samples:
    default: 25
    max: 1000
  confidence_level:
    default: 0.95
  time_step_increment:
    default: 0.2
    max: 5.0
  num_evictions:
    default: 1
  excluded_keys:
    default: [ ]
  prob_weight:
    default: 0.8
  conf_weight:
    default: 0.2
  return_all_scores:
    default: true
  return_prob_conf:
    default: true
  return_api_kwargs:
    default: true