# Continuos Delivery (CD): Manage reliable deployment of
# the API and documentation, ensuring that changes are quickly
# and safely delivered to production
name: Continuos Delivery (CD)

# Kill the current workflow if a
# new one get started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Run the workflow on every push or PR to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# The workflow is organized into three jobs:
# - Setup:
#     Checkout the repository on the current branch.
# - Deploy API (needs 'Setup'):
#     Deploy the API to k8s on Azure and test it (automatic
#     rollback if any of these two steps failed).
# - Deploy docs (needs 'Setup'):
#     Deploy documentation to GitHub Pages.
jobs:

  # -----------------------------
  # Setup
  # -----------------------------
  setup:
    runs-on: self-hosted
    steps:
      # Checkout the repository on
      # the current branch
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref }}

  # -----------------------------
  # Deploy API (needs 'Setup')
  # -----------------------------
  deploy_api:
    runs-on: self-hosted
    needs: setup
    steps:
      # Download the rendered k8s manifests
      # produced during CI
      - name: Download rendered k8s manifests
        uses: actions/download-artifact@v4
        with:
          name: ${{ vars.K8S_RENDERED_ARTIFACTS_NAME }}
          path: ${{ vars.K8S_RENDERED_ARTIFACTS_DIR }}

      # Login to Azure which hosts the API
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set the AKS context where the
      # API is deployed
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      # Deploy the API to k8s with automatic
      # rollback if any error occurred
      - name: Deploy API to k8s
        env:
          K8S_ROLLOUT_TIMEOUT: ${{ vars.K8S_ROLLOUT_TIMEOUT }}
          K8S_RENDERED_ARTIFACTS_DIR: ${{ vars.K8S_RENDERED_ARTIFACTS_DIR }}
        run: |
          # Apply all the deployment k8s manifests
          DEPLOYMENTS_APPLIED=()
          for file in $K8S_RENDERED_ARTIFACTS_DIR/*; do
              kubectl apply -f "$file"
              if grep -q "kind: Deployment" "$file"; then
                  DEPLOYMENTS_APPLIED+=("$file")
              fi
          done

          # Check rollout status for all deployments
          # with automatic rollback if any error occurred
          for file in "${DEPLOYMENTS_APPLIED[@]}"; do
              if ! kubectl rollout status -f "$file" --timeout=$K8S_ROLLOUT_TIMEOUT; then
                  for rollback_file in "${DEPLOYMENTS_APPLIED[@]}"; do
                      kubectl rollout undo -f "$rollback_file"
                  done
                  exit 1
              fi
          done

      # Test the API with automatic rollback
      # if any error occurred
      - name: Test API
        env:
          K8S_RENDERED_ARTIFACTS_DIR: ${{ vars.K8S_RENDERED_ARTIFACTS_DIR }}
        run: |
          export PYTHONPATH=$(pwd):$(pwd)/${{ vars.SRC_DIR }}

          # Identify all deployments
          DEPLOYMENTS=()
          for file in $K8S_RENDERED_ARTIFACTS_DIR/*; do
              if grep -q "kind: Deployment" "$file"; then
                  DEPLOYMENTS+=("$file")
              fi
          done

          # Run tests and capture exit code
          pytest -v -m "${{ vars.PYTEST_MARKER }}" ${{ vars.API_TESTS_DIR }}
          TEST_EXIT_CODE=$?

          # Rollback all deployments if any test failed
          if [ $TEST_EXIT_CODE -ne 0 ]; then
            for file in "${DEPLOYMENTS[@]}"; do
                kubectl rollout undo -f "$file"
            done
            exit $TEST_EXIT_CODE
          fi

  # -----------------------------
  # Deploy docs (needs 'Setup')
  # -----------------------------
  deploy_docs:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Download docs
        uses: actions/download-artifact@v4
        with:
          name: ${{ vars.DOCS_ARTIFACTS_NAME }}
          path: ${{ vars.DOCS_OUTPUT_DIR }}

      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ vars.DOCS_OUTPUT_DIR }}
          publish_branch: ${{ vars.DOCS_PUBLISH_BRANCH }}
