name: CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Code checking (ruff)
        run: ruff check . --diff

      - name: Code linting (pylint)
        run: |
          SCORE=$(pylint src | tee pylint.log | tail -1 | awk '{print $7}' | sed 's/\/10//')
          if (( $(echo "$SCORE < 8" | bc -l) )); then
            exit 1
          fi
