name: Continuos Integration (CI)

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: self-hosted
    steps:

      # ---------------------------
      # Setup
      # ---------------------------
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Azure login
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure-creds.json
          az login --service-principal --username $(jq -r .clientId azure-creds.json) \
                   --password $(jq -r .clientSecret azure-creds.json) \
                   --tenant $(jq -r .tenantId azure-creds.json)

      - name: Set up k8s manifests
        env:
          GITHUB_SHA: ${{ github.sha }}
          K8S_OVERLAYS_CI_PATH: ${{ vars.K8S_OVERLAYS_CI_PATH }}
          K8S_RENDERED_FILE: ${{ vars.K8S_RENDERED_FILE }}
          DOCKER_IMAGES: ${{ vars.DOCKER_IMAGES }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: |
          # Convert to array
          readarray -t DOCKER_IMAGES_ARRAY <<< "$DOCKER_IMAGES"

          # Inject Github SHA to all images
          cd ${K8S_OVERLAYS_CI_PATH}
          for svc in "${DOCKER_IMAGES_ARRAY[@]}"; do
              img_name=$(echo "$svc" | tr '_' '-')
              full_img="${ACR_NAME}.azurecr.io/${img_name}:${GITHUB_SHA}"
              kustomize edit set image "$svc=$full_img"
          done

          # Run Kustomize
          cd -
          kustomize build ${K8S_OVERLAYS_CI_PATH} > ${K8S_RENDERED_FILE}

      # ---------------------------
      # Code checks
      # ---------------------------
      - name: Check code quality
        run: ruff check ${{ vars.CODE_DIR }} --diff

      - name: Check code security
        run: bandit -r ${{ vars.SRC_DIR }} --severity-level ${{ vars.BANDIT_SEVERITY }}

      # ---------------------------
      # Linting
      # ---------------------------
      - name: Lint code
        run: pylint ${{ vars.SRC_DIR }} --fail-under=${{ vars.PYLINT_MIN_SCORE }}

      - name: Lint notebooks
        run: |
          files=$(find "${{ vars.NOTEBOOKS_DIR }}" -name '*.ipynb')
          if [ -n "$files" ]; then
            pynblint $files
          fi

      - name: Lint Dockerfiles
        run: |
          hadolint $(find . -name 'Dockerfile') --failure-threshold \
          "${{ vars.HADOLINT_FAILURE_THRESHOLD }}"

      # ---------------------------
      # Dependency checks
      # ---------------------------
      - name: Check dependency vulnerabilities
        env:
          PIP_AUDIT_IGNORE_VULNS: ${{ vars.PIP_AUDIT_IGNORE_VULNS }}
        run: |
          IGNORE_ARGS=""
          for v in $PIP_AUDIT_IGNORE_VULNS; do
            IGNORE_ARGS="$IGNORE_ARGS --ignore-vuln $v"
          done
          pip-audit $IGNORE_ARGS

      # ---------------------------
      # K8s checks
      # ---------------------------
      - name: Check k8s manifests
        run: checkov -d ${{ vars.K8S_RENDERED_FILE }} --framework ${{ vars.CHECKOV_FRAMEWORK }}

      - name: Check k8s readiness
        run: kube-score score ${{ vars.K8S_RENDERED_FILE }}

      # ---------------------------
      # Testing
      # ---------------------------
      - name: Run tests
        run: |
          export PYTHONPATH=${{ vars.SRC_DIR }}
          pytest -v -m "${{ vars.PYTEST_MARKER }}" ${{ vars.TESTS_DIR }}

      # ---------------------------
      # Docker image checks
      # ---------------------------
      - name: Check Docker images
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
          GITHUB_SHA: ${{ github.sha }}
          GATEWAY_API_PORT: ${{ vars.GATEWAY_API_PORT }}
          DECIDER_SERVICE_PORT: ${{ vars.DECIDER_SERVICE_PORT }}
          DECIDER_SERVICE_CHANNEL: ${{ vars.DECIDER_SERVICE_CHANNEL }}
          FEATURIZER_SERVICE_PORT: ${{ vars.FEATURIZER_SERVICE_PORT }}
          FEATURIZER_SERVICE_CHANNEL: ${{ vars.FEATURIZER_SERVICE_CHANNEL }}
          PREDICTOR_SERVICE_PORT: ${{ vars.PREDICTOR_SERVICE_PORT }}
          PREDICTOR_SERVICE_CHANNEL: ${{ vars.PREDICTOR_SERVICE_CHANNEL }}
          SCORER_SERVICE_PORT: ${{ vars.SCORER_SERVICE_PORT }}
          SCORER_SERVICE_CHANNEL: ${{ vars.SCORER_SERVICE_CHANNEL }}
          GRAFANA_LOKI_URL: ${{ vars.GRAFANA_LOKI_URL }}
          GRAFANA_LOKI_USER_ID: ${{ vars.GRAFANA_LOKI_USER_ID }}
          GRAFANA_LOKI_TOKEN: ${{ vars.GRAFANA_LOKI_TOKEN }}
          MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
          DAGS_HUB_REPO_OWNER: ${{ vars.DAGS_HUB_REPO_OWNER }}
          DAGS_HUB_TOKEN: ${{ vars.DAGS_HUB_TOKEN }}
        run: |
          # Clean up
          docker system prune -af || true
          sudo apt-get clean

          # Build and scan all the images
          readarray -t DOCKER_SERVICES_ARRAY <<< "$(echo "${{ vars.DOCKER_SERVICES }}" | tr -d '\r')"
          for img_name in "${DOCKER_SERVICES_ARRAY[@]}"; do
            # Get image
            img_name_normalized=$(echo "$img_name" | tr '_' '-')
            full_img="${{ secrets.ACR_NAME }}.azurecr.io/${img_name_normalized}:${{ github.sha }}"

            # Build image
            docker compose build "$img_name"

            # Scan image with Trivy
            trivy image \
              --exit-code ${{ vars.TRIVY_EXIT_CODE }} \
              --severity ${{ vars.TRIVY_SEVERITY }} \
              "$full_img"

            # Clean up
            docker rmi "$full_img" || true
            docker builder prune -af || true
            docker system prune -af || true
          done

      # ---------------------------
      # Docs generation
      # ---------------------------
      - name: Generate docs
        run: |
          PYTHONPATH=$(pwd)/${{ vars.SRC_DIR }} pdoc --html ${{ vars.SRC_DIR }}/ \
          --output-dir ${{ vars.DOCS_OUTPUT_DIR }} --force
